buildscript{
    repositories {
        mavenCentral()
        google()
    }
    dependencies {
        classpath 'net.serenity-bdd:serenity-single-page-report:4.3.2'
    }
}

plugins {
    id 'java'
    id 'idea'
    id 'io.freefair.lombok' version '9.2.0'
    id 'net.serenity-bdd.serenity-gradle-plugin' version '4.3.2'
}

group 'com.qa.challenge'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}


tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

ext{
    serenityVersion = '4.3.2'
    jacksonVersion = '3.1.2'
    cucumberVersion = '7.34.2'
    assertjVersion = '3.27.7'
    jupiterVersion = '6.0.1'
    logbackVersion = '1.5.6'
    dataFakerVersion = '2.5.3'
}

serenity {
    reports = ["single-page-html"]
}

dependencies {
    implementation "net.serenity-bdd:serenity-core:$rootProject.ext.serenityVersion"
    implementation "net.serenity-bdd:serenity-junit5:$rootProject.ext.serenityVersion"
    implementation "net.serenity-bdd:serenity-screenplay:$rootProject.ext.serenityVersion"
    implementation "net.serenity-bdd:serenity-cucumber:$rootProject.ext.serenityVersion"
    implementation "net.serenity-bdd:serenity-screenplay-rest:$rootProject.ext.serenityVersion"
    implementation "net.serenity-bdd:serenity-reports:$rootProject.ext.serenityVersion"
    implementation "tools.jackson.core:jackson-databind:$rootProject.ext.jacksonVersion"
    testImplementation "io.cucumber:cucumber-junit-platform-engine:$rootProject.ext.cucumberVersion"
    testImplementation "org.junit.platform:junit-platform-suite:$rootProject.ext.jupiterVersion"
    testImplementation "org.junit.jupiter:junit-jupiter-api:${jupiterVersion}"
    testImplementation "net.serenity-bdd:serenity-ensure:$rootProject.ext.serenityVersion"
    testImplementation "org.assertj:assertj-core:$rootProject.ext.assertjVersion"
    testImplementation "ch.qos.logback:logback-classic:$rootProject.ext.logbackVersion"
    testImplementation "net.datafaker:datafaker:$rootProject.ext.dataFakerVersion"
}

test {
    useJUnitPlatform()
    testLogging {
        showStandardStreams = true
    }
}

gradle.startParameter.continueOnFailure = true
test.finalizedBy(aggregate)