serenity.project.name = qa-rest-screenplay-challenge
serenity.console.colors = true
serenity.logging = VERBOSE
serenity.dry.run=false
serenity.test.root=com.qa.challenge
serenity.reports.show.step.details = true
report.tagtypes=capability,feature
serenity.report.encoding=UTF-8
serenity.encoding=UTF-8